nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  volumes:
    - .:/var/www/html
  links:
    - php
  ports:
    - "80:80"
php:
  image: bitnami/php-fpm:7.2
  volumes:
    - .:/var/www/html
  working_dir: /var/www/html/shop
  links:
    - mysql
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_DATABASE: shop
    DB_USERNAME: root
    DB_PASSWORD: secret
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
mysql:
  image: mysql:5.7
  ports:
    - "3333:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: shop
    MYSQL_USER: root
    MYSQL_PASSWORD: secret
cache:
  image: memcached
